//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xls_Trans_Tool_Wpf {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Wording {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Wording() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xls_Trans_Tool_Wpf.Wording", typeof(Wording).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t find right columns.
        /// </summary>
        public static string CantFindRightColumns {
            get {
                return ResourceManager.GetString("CantFindRightColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Find Right Sheet.
        /// </summary>
        public static string CantFindRightSheet {
            get {
                return ResourceManager.GetString("CantFindRightSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1. Press [Load] to select the file that want to transfer
        ///Step 2. After lower left corner show &quot;Load Success&quot;, Press [Save] to start transfer, when finished, lower left corner will show &quot;Save Success&quot; and autoclose in 1sec.
        ///
        ///-Save File Location and file name can modify by yourself
        ///-Sales and Sales Assistant field not must required
        ///-Check Shipping Instruction,Priority &amp; Order Type...etc check box if you need it in Summary
        ///-Check Additional Optional 1~5 if you need it in Summary.
        /// </summary>
        public static string Guide {
            get {
                return ResourceManager.GetString("Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Height:.
        /// </summary>
        public static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Fail..
        /// </summary>
        public static string LoadFail {
            get {
                return ResourceManager.GetString("LoadFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load File Location.
        /// </summary>
        public static string LoadFileLocation {
            get {
                return ResourceManager.GetString("LoadFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading File....
        /// </summary>
        public static string LoadingFile {
            get {
                return ResourceManager.GetString("LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Success, Got {0} rows..
        /// </summary>
        public static string LoadSuccessGotrows {
            get {
                return ResourceManager.GetString("LoadSuccessGotrows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Error: {0}.
        /// </summary>
        public static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales:.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Assistant:.
        /// </summary>
        public static string SalesAssistant {
            get {
                return ResourceManager.GetString("SalesAssistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File Location.
        /// </summary>
        public static string SaveFileLocation {
            get {
                return ResourceManager.GetString("SaveFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving File....
        /// </summary>
        public static string SaveingFile {
            get {
                return ResourceManager.GetString("SaveingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Success..
        /// </summary>
        public static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong header: {0}!={1}.
        /// </summary>
        public static string WrongHeader {
            get {
                return ResourceManager.GetString("WrongHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong header numbers {0}!={1}.
        /// </summary>
        public static string WrongHeaderNumbers {
            get {
                return ResourceManager.GetString("WrongHeaderNumbers", resourceCulture);
            }
        }
    }
}
